from datetime import datetime
from typing import Optional

from fastapi import APIRouter, HTTPException, Query, Request
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from src.core.billing import calculate_fee
from src.models.database import AsyncSessionLocal
from src.models.models import Bill, ChargeOrder, Vehicle

router = APIRouter()

# Lightweight browser-session lock for demo/acceptance flows.
# Key: vehicle plate, value: opaque session id generated by the browser.
ACTIVE_VEHICLE_SESSIONS: dict[str, str] = {}


def _normalize_vehicle_id(vehicle_id: str) -> str:
    return (vehicle_id or "").strip().upper()


def _verify_vehicle_session(vehicle_id: str, session_id: Optional[str]) -> str:
    vid = _normalize_vehicle_id(vehicle_id)
    if not vid:
        raise HTTPException(status_code=400, detail="vehicle_id is required")
    if not session_id:
        raise HTTPException(status_code=401, detail="Please register or login this vehicle first")
    active = ACTIVE_VEHICLE_SESSIONS.get(vid)
    if active != session_id:
        raise HTTPException(status_code=403, detail="This vehicle is not logged in by current page")
    return vid


def _parse_datetime(value: str) -> datetime:
    dt_str = (value or "").strip().replace("T", " ")
    if len(dt_str) <= 8:
        dt_str = f"{datetime.now().strftime('%Y-%m-%d')} {dt_str}"
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M"):
        try:
            return datetime.strptime(dt_str, fmt)
        except ValueError:
            continue
    raise HTTPException(status_code=400, detail="Invalid datetime")


async def _build_vehicle_status(vehicle_id: str, request: Request) -> dict:
    scheduler = request.app.state.scheduler
    status = scheduler.get_system_status()
    qdata = scheduler.get_waiting_area()

    for idx, q in enumerate(qdata.get("pending", [])):
        if q["vehicle_id"] == vehicle_id:
            start_time = q.get("requested_start_time")
            if hasattr(start_time, "strftime"):
                start_time = start_time.strftime("%Y-%m-%d %H:%M:%S")
            return {
                "status": "SCHEDULED",
                "area": "scheduled",
                "area_detail": f"预约生效时间 {start_time or '--'}",
                "queue_id": "S",
                "queue_position": idx,
                "order_id": q["order_id"],
                "estimated_wait_time": "-",
            }

    for idx, q in enumerate(qdata.get("fast_waiting", [])):
        if q["vehicle_id"] == vehicle_id:
            return {
                "status": "WAITING",
                "area": "waiting_area",
                "area_detail": f"Fast waiting #{idx + 1}",
                "queue_id": "F",
                "queue_position": idx,
                "order_id": q["order_id"],
                "estimated_wait_time": "15",
            }

    for idx, q in enumerate(qdata.get("slow_waiting", [])):
        if q["vehicle_id"] == vehicle_id:
            return {
                "status": "WAITING",
                "area": "waiting_area",
                "area_detail": f"Slow waiting #{idx + 1}",
                "queue_id": "T",
                "queue_position": idx,
                "order_id": q["order_id"],
                "estimated_wait_time": "30",
            }

    for p in status.get("piles", []):
        for idx, q in enumerate(p.get("queue_items", [])):
            if q["vehicle_id"] == vehicle_id:
                state = "CHARGING" if idx == 0 and p["status"] == "CHARGING" else "QUEUING"
                return {
                    "status": state,
                    "area": "charging_area",
                    "area_detail": f"{p['pile_id']} position {idx + 1}",
                    "queue_id": p["pile_id"],
                    "queue_position": idx,
                    "order_id": q["order_id"],
                    "estimated_wait_time": "0",
                }

    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(ChargeOrder)
            .where(ChargeOrder.vehicle_id == vehicle_id)
            .order_by(ChargeOrder.id.desc())
        )
        order = result.scalars().first()
        if order:
            return {
                "status": order.status,
                "area": "left_area",
                "area_detail": order.status,
                "order_id": order.id,
                "queue_id": order.pile_id,
                "queue_position": 0,
                "estimated_wait_time": "-",
            }

    return {
        "status": "REGISTERED",
        "area": "not_submitted",
        "area_detail": "Vehicle registered",
        "order_id": None,
        "queue_id": None,
        "queue_position": 0,
        "estimated_wait_time": "-",
    }


class ChargeReqBody(BaseModel):
    vehicle_id: str
    charge_type: str
    requested_capacity: float
    session_id: Optional[str] = None
    start_datetime: Optional[str] = None


@router.post("/user/charge/request")
async def user_charge_request(body: ChargeReqBody, request: Request):
    from src.api.schemas import ChargeRequest

    vehicle_id = _verify_vehicle_session(body.vehicle_id, body.session_id)
    requested_start_time = None
    if body.start_datetime:
        requested_start_time = _parse_datetime(body.start_datetime)
        allowed_start = getattr(request.app.state, "clock_allowed_start", None)
        allowed_end = getattr(request.app.state, "clock_allowed_end", None)
        if allowed_start and requested_start_time < datetime.strptime(allowed_start, "%Y-%m-%d %H:%M:%S"):
            raise HTTPException(status_code=400, detail="Selected start time is earlier than admin allowed start")
        if allowed_end and requested_start_time > datetime.strptime(allowed_end, "%Y-%m-%d %H:%M:%S"):
            raise HTTPException(status_code=400, detail="Selected start time is later than admin allowed end")

    async with AsyncSessionLocal() as session:
        vehicle = (
            await session.execute(select(Vehicle).where(Vehicle.vehicle_id == vehicle_id))
        ).scalars().first()
        if vehicle is None:
            raise HTTPException(status_code=404, detail="Vehicle must be registered before submitting charge request")

    real_req = ChargeRequest(
        vehicle_id=vehicle_id,
        charge_type=body.charge_type,
        requested_kwh=body.requested_capacity,
        requested_start_time=requested_start_time,
    )
    result = await request.app.state.scheduler.submit_request(real_req)
    if result.get("status") == "failed":
        raise HTTPException(status_code=400, detail=result.get("message"))
    return result


@router.get("/user/vehicle/status/{vehicle_id}")
async def get_vehicle_status(
    vehicle_id: str,
    request: Request,
    session_id: Optional[str] = Query(None),
):
    vehicle_id = _verify_vehicle_session(vehicle_id, session_id)
    return await _build_vehicle_status(vehicle_id, request)


class CancelReqBody(BaseModel):
    vehicle_id: str
    session_id: Optional[str] = None


@router.post("/user/charge/cancel")
async def cancel_charge(body: CancelReqBody, request: Request):
    vehicle_id = _verify_vehicle_session(body.vehicle_id, body.session_id)
    scheduler = request.app.state.scheduler
    status = scheduler.get_system_status()
    qdata = scheduler.get_waiting_area()
    oid = None

    for q in qdata.get("fast_waiting", []):
        if q["vehicle_id"] == vehicle_id:
            oid = q["order_id"]
    for q in qdata.get("slow_waiting", []):
        if q["vehicle_id"] == vehicle_id:
            oid = q["order_id"]
    for p in status.get("piles", []):
        for q in p.get("queue_items", []):
            if q["vehicle_id"] == vehicle_id:
                oid = q["order_id"]

    if oid:
        res = await scheduler.cancel_request(oid)
        if res.get("status") == "failed":
            raise HTTPException(status_code=400, detail=res.get("message"))
    return {"status": "success"}


@router.get("/queue/list")
async def get_queue_list(request: Request):
    qdata = request.app.state.scheduler.get_waiting_area()
    result = []
    for q in qdata.get("fast_waiting", []):
        result.append({
            "queue_id": q.get("queue_number", "F"),
            "vehicle_id": q.get("vehicle_id", ""),
            "queue_duration": 0,
            "requested_capacity": q.get("requested_kwh", 0),
        })
    for q in qdata.get("slow_waiting", []):
        result.append({
            "queue_id": q.get("queue_number", "T"),
            "vehicle_id": q.get("vehicle_id", ""),
            "queue_duration": 0,
            "requested_capacity": q.get("requested_kwh", 0),
        })
    return result


@router.get("/pile/status")
async def get_pile_status(request: Request):
    status = request.app.state.scheduler.get_system_status()
    res = []
    for p in status.get("piles", []):
        is_charging = p["status"] == "CHARGING"
        qi = p.get("queue_items", [])
        current_user = qi[0]["vehicle_id"] if is_charging and qi else "none"
        cur_soc = p.get("current_soc", 0.0)
        dur = p.get("charged_duration", 0)
        res.append({
            "pile_id": p["pile_id"],
            "status": "charging" if is_charging else ("fault" if p["status"] == "FAULT" else "idle"),
            "current_user": current_user,
            "charged_electricity": cur_soc * 100 if is_charging else 0,
            "charged_duration": dur or 0,
            "power": p.get("power", 0),
        })
    return res


def _bill_to_detail(bill: Bill) -> dict:
    detail = {
        "peak_minutes": 0,
        "flat_minutes": 0,
        "valley_minutes": 0,
        "peak_kwh": 0.0,
        "peak_fee": 0.0,
        "flat_kwh": 0.0,
        "flat_fee": 0.0,
        "valley_kwh": 0.0,
        "valley_fee": 0.0,
        "segments": [],
    }
    for seg in bill.details or []:
        period = seg.period or ""
        if period in ("peak", "flat", "valley"):
            detail[f"{period}_minutes"] += seg.duration_minutes or 0
            detail[f"{period}_kwh"] += seg.kwh or 0.0
            detail[f"{period}_fee"] += seg.fee or 0.0
        detail["segments"].append({
            "period": seg.period,
            "start": seg.start_time,
            "end": seg.end_time,
            "minutes": seg.duration_minutes or 0,
            "kwh": seg.kwh or 0.0,
            "rate": seg.rate or 0.0,
            "fee": seg.fee or 0.0,
        })
    return detail


@router.get("/user/orders/{vehicle_id}")
async def get_orders(
    vehicle_id: str,
    session_id: Optional[str] = Query(None),
):
    vehicle_id = _verify_vehicle_session(vehicle_id, session_id)
    async with AsyncSessionLocal() as session:
        orders = (
            await session.execute(
                select(ChargeOrder)
                .where(ChargeOrder.vehicle_id == vehicle_id)
                .order_by(ChargeOrder.id.desc())
            )
        ).scalars().all()
        bills = (
            await session.execute(
                select(Bill)
                .options(selectinload(Bill.details))
                .where(Bill.vehicle_id == vehicle_id)
                .order_by(Bill.id.desc())
            )
        ).scalars().unique().all()

    bills_by_order = {b.order_id: b for b in bills}
    out = []
    for o in orders:
        bill = bills_by_order.get(o.id)
        start_time = bill.charge_start_time if bill else o.charge_start_time
        end_time = bill.charge_end_time if bill else o.charge_end_time
        item = {
            "order_id": o.id,
            "status": o.status,
            "bill_code": (bill.bill_code if bill else o.bill_code) or f"Order-{o.id}",
            "created_at": o.created_at.isoformat() if o.created_at else None,
            "pile_id": o.pile_id or "--",
            "electricity": (bill.total_power if bill else o.total_power) or 0,
            "duration": (bill.charge_duration if bill else o.charge_duration) or 0,
            "start_time": start_time.isoformat() if start_time else "--",
            "end_time": end_time.isoformat() if end_time else "--",
            "power_fee": (bill.power_fee if bill else o.power_fee) or 0,
            "service_fee": (bill.service_fee if bill else o.service_fee) or 0,
            "total_fee": (bill.total_fee if bill else o.total_fee) or 0,
            "detail": _bill_to_detail(bill) if bill else None,
        }
        if item["detail"] is None and o.charge_start_time and o.charge_end_time and o.total_power and o.total_power > 0:
            item["detail"] = calculate_fee(o.charge_start_time, o.charge_end_time, o.total_power).get("detail")
        out.append(item)
    return out


@router.get("/order/{order_id}")
async def get_order_detail(order_id: int):
    async with AsyncSessionLocal() as session:
        o = await session.get(ChargeOrder, order_id)
    if not o:
        raise HTTPException(status_code=404)
    return {
        "order_id": o.id,
        "pile_id": o.pile_id,
        "electricity": o.total_power or 0,
        "duration": o.charge_duration or 0,
        "electricity_fee": o.power_fee or 0,
        "service_fee": o.service_fee or 0,
        "total_fee": o.total_fee or 0,
        "start_time": o.charge_start_time.isoformat() if o.charge_start_time else None,
        "end_time": o.charge_end_time.isoformat() if o.charge_end_time else None,
        "finished_at": o.finished_at.isoformat() if o.finished_at else None,
    }


class PowerConfigBody(BaseModel):
    fast_power: float
    slow_power: float


@router.post("/compat/config/power")
async def update_power_config(body: PowerConfigBody, request: Request):
    scheduler = request.app.state.scheduler
    return await scheduler.update_power(body.fast_power, body.slow_power)


@router.get("/compat/dump")
async def compat_dump(request: Request):
    scheduler = request.app.state.scheduler
    status = scheduler.get_system_status()
    for p in status["piles"]:
        is_charging = p["status"] == "CHARGING"
        qi = p.get("queue_items", [])
        if is_charging and qi:
            p["vehicle_id"] = qi[0]["vehicle_id"]
            req = qi[0].get("requested_kwh") or 1
            p["current_soc"] = qi[0].get("charged_kwh", 0) / req
            p["target_soc"] = 1.0
        else:
            p["vehicle_id"] = "undef"
            p["current_soc"] = 0
            p["target_soc"] = 1.0

    qdata = scheduler.get_waiting_area()
    status["fast_queue"] = []
    for q in qdata["fast_waiting"]:
        status["fast_queue"].append({
            "vehicle_id": q["vehicle_id"],
            "queue_num": q["queue_number"],
            "requested_capacity": q["requested_kwh"],
            "queue_duration": 0,
            "battery_capacity": q.get("battery_capacity_kwh", 100),
        })
    status["slow_queue"] = []
    for q in qdata["slow_waiting"]:
        status["slow_queue"].append({
            "vehicle_id": q["vehicle_id"],
            "queue_num": q["queue_number"],
            "requested_capacity": q["requested_kwh"],
            "queue_duration": 0,
            "battery_capacity": q.get("battery_capacity_kwh", 100),
        })
    status["fast_queue_count"] = status["fast_waiting_count"]
    status["slow_queue_count"] = status["slow_waiting_count"]
    return status


class VehicleRegBody(BaseModel):
    vehicle_id: str
    battery_capacity_kwh: float = 60.0
    current_kwh: float = 0.0
    session_id: Optional[str] = None


@router.post("/vehicle/register")
async def register_vehicle_compat(body: VehicleRegBody, request: Request):
    vehicle_id = _normalize_vehicle_id(body.vehicle_id)
    if not vehicle_id:
        raise HTTPException(status_code=400, detail="vehicle_id is required")
    if not body.session_id:
        raise HTTPException(status_code=400, detail="session_id is required")
    if body.current_kwh > body.battery_capacity_kwh:
        raise HTTPException(status_code=400, detail="current_kwh cannot exceed battery_capacity_kwh")

    active = ACTIVE_VEHICLE_SESSIONS.get(vehicle_id)
    if active and active != body.session_id:
        raise HTTPException(status_code=409, detail="This vehicle plate is already logged in elsewhere")

    async with AsyncSessionLocal() as session:
        existing = (
            await session.execute(select(Vehicle).where(Vehicle.vehicle_id == vehicle_id))
        ).scalars().first()
        if existing:
            ACTIVE_VEHICLE_SESSIONS[vehicle_id] = body.session_id
            return {
                "status": "exists",
                "vehicle_id": existing.vehicle_id,
                "battery_capacity_kwh": existing.battery_capacity_kwh,
                "current_kwh": existing.current_kwh,
                "session_id": body.session_id,
                "current_status": await _build_vehicle_status(vehicle_id, request),
            }

        vehicle = Vehicle(
            vehicle_id=vehicle_id,
            battery_capacity_kwh=body.battery_capacity_kwh,
            current_kwh=body.current_kwh,
        )
        session.add(vehicle)
        await session.commit()
        await session.refresh(vehicle)

    ACTIVE_VEHICLE_SESSIONS[vehicle_id] = body.session_id
    return {
        "status": "created",
        "vehicle_id": vehicle.vehicle_id,
        "battery_capacity_kwh": vehicle.battery_capacity_kwh,
        "current_kwh": vehicle.current_kwh,
        "session_id": body.session_id,
        "current_status": await _build_vehicle_status(vehicle.vehicle_id, request),
    }


@router.get("/vehicle/info/{vehicle_id}")
async def get_vehicle_info_compat(
    vehicle_id: str,
    request: Request,
    session_id: Optional[str] = Query(None),
):
    vehicle_id = _normalize_vehicle_id(vehicle_id)
    async with AsyncSessionLocal() as session:
        vehicle = (
            await session.execute(select(Vehicle).where(Vehicle.vehicle_id == vehicle_id))
        ).scalars().first()

    if vehicle is None:
        return {"status": "not_found", "vehicle_id": vehicle_id}

    active = ACTIVE_VEHICLE_SESSIONS.get(vehicle.vehicle_id)
    return {
        "status": "found",
        "vehicle_id": vehicle.vehicle_id,
        "battery_capacity_kwh": vehicle.battery_capacity_kwh,
        "current_kwh": vehicle.current_kwh,
        "logged_in_here": active == session_id,
        "locked_elsewhere": bool(active and active != session_id),
        "current_status": await _build_vehicle_status(vehicle.vehicle_id, request),
    }


class VehicleLogoutBody(BaseModel):
    vehicle_id: str
    session_id: Optional[str] = None


@router.post("/vehicle/logout")
async def logout_vehicle_compat(body: VehicleLogoutBody):
    vehicle_id = _normalize_vehicle_id(body.vehicle_id)
    if ACTIVE_VEHICLE_SESSIONS.get(vehicle_id) == body.session_id:
        ACTIVE_VEHICLE_SESSIONS.pop(vehicle_id, None)
    return {"status": "success"}


class UserClockSetBody(BaseModel):
    datetime: str


@router.get("/user/clock")
async def get_user_clock(request: Request):
    scheduler = request.app.state.scheduler
    return {
        "current_virtual_time": scheduler.clock.get_time().strftime("%Y-%m-%d %H:%M:%S"),
        "ratio": scheduler.clock.ratio,
        "running": scheduler.clock.running,
        "allowed_start": getattr(request.app.state, "clock_allowed_start", None),
        "allowed_end": getattr(request.app.state, "clock_allowed_end", None),
    }


@router.put("/user/clock")
async def set_user_clock(body: UserClockSetBody, request: Request):
    target = _parse_datetime(body.datetime)
    allowed_start = getattr(request.app.state, "clock_allowed_start", None)
    allowed_end = getattr(request.app.state, "clock_allowed_end", None)
    if allowed_start and target < datetime.strptime(allowed_start, "%Y-%m-%d %H:%M:%S"):
        raise HTTPException(status_code=400, detail="Selected start time is earlier than admin allowed start")
    if allowed_end and target > datetime.strptime(allowed_end, "%Y-%m-%d %H:%M:%S"):
        raise HTTPException(status_code=400, detail="Selected start time is later than admin allowed end")

    request.app.state.scheduler.clock.set_time(target)
    return {
        "status": "success",
        "current_virtual_time": request.app.state.scheduler.clock.get_time().strftime("%Y-%m-%d %H:%M:%S"),
        "running": request.app.state.scheduler.clock.running,
    }


@router.post("/user/clock/start")
async def start_user_clock(request: Request):
    request.app.state.scheduler.clock.start()
    return {
        "status": "success",
        "current_virtual_time": request.app.state.scheduler.clock.get_time().strftime("%Y-%m-%d %H:%M:%S"),
        "running": request.app.state.scheduler.clock.running,
    }


@router.post("/user/clock/pause")
async def pause_user_clock(request: Request):
    request.app.state.scheduler.clock.pause()
    return {
        "status": "success",
        "current_virtual_time": request.app.state.scheduler.clock.get_time().strftime("%Y-%m-%d %H:%M:%S"),
        "running": request.app.state.scheduler.clock.running,
    }
